package com.izettle.java;

public enum CurrencyId {

	AED, AFA, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZM, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, BTN,
	BWP, BYR, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CSD, CUC, CUP, CVE, CYP, CZK, DJF, DKK, DOP, DZD, EEK, EGP,
	ERN, ETB, EUR, FJD, FKP, GBP, GEL, GGP, GHC, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, IMP,
	INR, IQD, IRR, ISK, JEP, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL,
	LTL, LVL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MTL, MUR, MVR, MWK, MXN, MYR, MZM, NAD, NGN, NIO, NOK,
	NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RUB, RWF, SAR, SBD, SCR, SDD, SEK, SGD, SHP, SIT,
	SKK, SLL, SOS, SPL, SRD, STD, SVC, SYP, SZL, THB, TJS, TMM, TND, TOP, TRL, TRY, TTD, TVD, TWD, TZS, UAH, UGX,
	USD, UYU, UZS, VEB, VND, VUV, WST, XAF, XAG, XAU, XCD, XDR, XOF, XPD, XPF, XPT, YER, ZAR, ZMK, ZWD;
}
